services:
  stats-server:
    build: stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat


  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  ewm-service:
    ports:
      - "8080:8080"
    environment:
      - CLIENT_URL=http://stats-server:9090
      - STRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/evm-main
      - STRING_DATASOURCE_USERNAME=main
      - STRING_DATASOURCE_PASSWORD=main

#
#  ewm-db:
#   image: postgres:16.1
